apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: "cno-unset-target-mtu-master"
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain,FileContent
          mode: 420
          overwrite: true
          path: /etc/testFile
  extensions: null
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""